# Site settings
title: ClintKo's Blog
description: "A minimal blog template, build with Jekyll."
url: "https://clintko.github.io/blogv2/"
author:
  name: "Kuei-Yueh Ko (Clinton Ko)"
  email: "clint00724@gmail.com"
  url: "https://clintko.github.io/blogv2//about"

# Build settings
baseurl: /blogv2/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
